pipelines:
  - name: pipeline_A_TemplateSync_6731_002
    steps:
      - name: A_TemplateSync_6731_002
        type: Bash
        execution:
          onExecute:
            - echo "Running test case A_TemplateSync_6731_002"
